spring:
  application:
  name: configserver
  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: "file:///C://users//skoziol/config" or "classpath:/config
        git:
          uri: "https://github.com/szykoz/mybank-config.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true

server:
  port: 8071
